// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationAddMarks.Models;

#nullable disable

namespace WebApplicationAddMarks.Migrations
{
    [DbContext(typeof(AddMarksContext))]
    partial class AddMarksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplicationAddMarks.Models.Mark", b =>
                {
                    b.Property<int>("MarkId")
                        .HasColumnType("int");

                    b.Property<int>("Mark1")
                        .HasColumnType("int")
                        .HasColumnName("Mark");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("MarkId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("WebApplicationAddMarks.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudentId");

                    b.HasIndex(new[] { "FirstName", "LastName" }, "UQ_Students_FullName")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("WebApplicationAddMarks.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SubjectId");

                    b.HasIndex(new[] { "SubjectName" }, "UQ_Subjects_SubjectName")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("WebApplicationAddMarks.Models.Mark", b =>
                {
                    b.HasOne("WebApplicationAddMarks.Models.Student", "Student")
                        .WithMany("Marks")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Marks__StudentId__5BE2A6F2");

                    b.HasOne("WebApplicationAddMarks.Models.Subject", "Subject")
                        .WithMany("Marks")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK__Marks__SubjectId__5CD6CB2B");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("WebApplicationAddMarks.Models.Student", b =>
                {
                    b.Navigation("Marks");
                });

            modelBuilder.Entity("WebApplicationAddMarks.Models.Subject", b =>
                {
                    b.Navigation("Marks");
                });
#pragma warning restore 612, 618
        }
    }
}
